{"name": "test_login_performance[user_data1]", "status": "broken", "statusDetails": {"message": "RuntimeError: 浏览器启动失败: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n\tGetHandleVerifier [0x0xccfd23+62915]\n\tGetHandleVerifier [0x0xccfd64+62980]\n\t(No symbol) [0x0xb03e13]\n\t(No symbol) [0x0xb378e8]\n\t(No symbol) [0x0xb331e9]\n\t(No symbol) [0x0xb7ce32]\n\t(No symbol) [0x0xb7c74a]\n\t(No symbol) [0x0xb711d6]\n\t(No symbol) [0x0xb40833]\n\t(No symbol) [0x0xb416a4]\n\tGetHandleVerifier [0x0xf38d13+2590131]\n\tGetHandleVerifier [0x0xf33f5a+2570234]\n\tGetHandleVerifier [0x0xcf59da+217722]\n\tGetHandleVerifier [0x0xce6048+153832]\n\tGetHandleVerifier [0x0xcec4ad+179533]\n\tGetHandleVerifier [0x0xcd7728+94152]\n\tGetHandleVerifier [0x0xcd78b2+94546]\n\tGetHandleVerifier [0x0xcc2bca+9322]\n\tBaseThreadInitThunk [0x0x75fb5d49+25]\n\tRtlInitializeExceptionChain [0x0x7777d1ab+107]\n\tRtlGetAppContainerNamedObjectPath [0x0x7777d131+561]", "trace": "self = <core.browser_manager.BrowserManager object at 0x04B45918>\nbrowser_type = 'chrome'\n\n    def start_browser(self,browser_type=\"chrome\"):\n        \"\"\"启动浏览器\"\"\"\n        try:\n            self._create_user_data_dir()\n            self.options = self._setup_options()\n            self.logger.info(f\"启动Chrome(自我驱动管理),用户数据目录:{self.user_data_dir}\")\n            print(f\"启动Chrome,用户数据目录:{self.user_data_dir}\")\n            # print(f\"无头模式状态: {self.headless_mode}\")\n    \n            # 启动Chrome浏览器服务\n            service = ChromeService(executable_path=ChromeDriverManager().install())\n            # 创建 webDriver 实例\n>           driver = webdriver.Chrome(service=service, options=self.options)\n\n..\\core\\browser_manager.py:90: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nD:\\Python312-32\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py:45: in __init__\n    super().__init__(\nD:\\Python312-32\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py:66: in __init__\n    super().__init__(command_executor=executor, options=options)\nD:\\Python312-32\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:250: in __init__\n    self.start_session(capabilities)\nD:\\Python312-32\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:342: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\nD:\\Python312-32\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:429: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x04EB6798>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: probably user data d...]\\\\n\\\\tRtlInitializeExceptionChain [0x0x7777d1ab+107]\\\\n\\\\tRtlGetAppContainerNamedObjectPath [0x0x7777d131+561]\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nE       Stacktrace:\nE       \tGetHandleVerifier [0x0xccfd23+62915]\nE       \tGetHandleVerifier [0x0xccfd64+62980]\nE       \t(No symbol) [0x0xb03e13]\nE       \t(No symbol) [0x0xb378e8]\nE       \t(No symbol) [0x0xb331e9]\nE       \t(No symbol) [0x0xb7ce32]\nE       \t(No symbol) [0x0xb7c74a]\nE       \t(No symbol) [0x0xb711d6]\nE       \t(No symbol) [0x0xb40833]\nE       \t(No symbol) [0x0xb416a4]\nE       \tGetHandleVerifier [0x0xf38d13+2590131]\nE       \tGetHandleVerifier [0x0xf33f5a+2570234]\nE       \tGetHandleVerifier [0x0xcf59da+217722]\nE       \tGetHandleVerifier [0x0xce6048+153832]\nE       \tGetHandleVerifier [0x0xcec4ad+179533]\nE       \tGetHandleVerifier [0x0xcd7728+94152]\nE       \tGetHandleVerifier [0x0xcd78b2+94546]\nE       \tGetHandleVerifier [0x0xcc2bca+9322]\nE       \tBaseThreadInitThunk [0x0x75fb5d49+25]\nE       \tRtlInitializeExceptionChain [0x0x7777d1ab+107]\nE       \tRtlGetAppContainerNamedObjectPath [0x0x7777d131+561]\n\nD:\\Python312-32\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:232: SessionNotCreatedException\n\nDuring handling of the above exception, another exception occurred:\n\nfixturedef = <FixtureDef argname='browser' scope='function' baseid='tests'>\nrequest = <SubRequest 'browser' for <Function test_login_performance[user_data1]>>\n\n    @pytest.hookimpl(wrapper=True)\n    def pytest_fixture_setup(fixturedef: FixtureDef, request) -> object | None:\n        asyncio_mode = _get_asyncio_mode(request.config)\n        if not _is_asyncio_fixture_function(fixturedef.func):\n            if asyncio_mode == Mode.STRICT:\n                # Ignore async fixtures without explicit asyncio mark in strict mode\n                # This applies to pytest_trio fixtures, for example\n>               return (yield)\n\nD:\\Python312-32\\Lib\\site-packages\\pytest_asyncio\\plugin.py:681: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nconftest.py:16: in browser\n    driver = manager.start_browser()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <core.browser_manager.BrowserManager object at 0x04B45918>\nbrowser_type = 'chrome'\n\n    def start_browser(self,browser_type=\"chrome\"):\n        \"\"\"启动浏览器\"\"\"\n        try:\n            self._create_user_data_dir()\n            self.options = self._setup_options()\n            self.logger.info(f\"启动Chrome(自我驱动管理),用户数据目录:{self.user_data_dir}\")\n            print(f\"启动Chrome,用户数据目录:{self.user_data_dir}\")\n            # print(f\"无头模式状态: {self.headless_mode}\")\n    \n            # 启动Chrome浏览器服务\n            service = ChromeService(executable_path=ChromeDriverManager().install())\n            # 创建 webDriver 实例\n            driver = webdriver.Chrome(service=service, options=self.options)\n    \n            # 注入 JS 脚本，将 navigator.webdriver 设置为 undefined\n            driver.execute_cdp_cmd(\"Page.addScriptToEvaluateOnNewDocument\", {\n                \"source\": \"Object.defineProperty(navigator, 'webdriver', {get: () => undefined})\"\n            })\n    \n            #把局部driver 赋值给self.driver\n            self.driver = driver\n            #智能等待，元素是否出现在页面上并且是可见的，最多等待10S。\n            self.wait = WebDriverWait(self.driver, 10)\n    \n            print(\"Chrome启动成功！\")\n            self.logger.info(\"Chrome启动成功！\")\n    \n            return self.driver\n    \n        except Exception as e:\n            self.logger.error(f\"浏览器启动失败:{e}\",exc_info=True)\n            self._cleanup_user_data_dir()\n>           raise RuntimeError(f\"浏览器启动失败: {str(e)}\")\nE           RuntimeError: 浏览器启动失败: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nE           Stacktrace:\nE           \tGetHandleVerifier [0x0xccfd23+62915]\nE           \tGetHandleVerifier [0x0xccfd64+62980]\nE           \t(No symbol) [0x0xb03e13]\nE           \t(No symbol) [0x0xb378e8]\nE           \t(No symbol) [0x0xb331e9]\nE           \t(No symbol) [0x0xb7ce32]\nE           \t(No symbol) [0x0xb7c74a]\nE           \t(No symbol) [0x0xb711d6]\nE           \t(No symbol) [0x0xb40833]\nE           \t(No symbol) [0x0xb416a4]\nE           \tGetHandleVerifier [0x0xf38d13+2590131]\nE           \tGetHandleVerifier [0x0xf33f5a+2570234]\nE           \tGetHandleVerifier [0x0xcf59da+217722]\nE           \tGetHandleVerifier [0x0xce6048+153832]\nE           \tGetHandleVerifier [0x0xcec4ad+179533]\nE           \tGetHandleVerifier [0x0xcd7728+94152]\nE           \tGetHandleVerifier [0x0xcd78b2+94546]\nE           \tGetHandleVerifier [0x0xcc2bca+9322]\nE           \tBaseThreadInitThunk [0x0x75fb5d49+25]\nE           \tRtlInitializeExceptionChain [0x0x7777d1ab+107]\nE           \tRtlGetAppContainerNamedObjectPath [0x0x7777d131+561]\n\n..\\core\\browser_manager.py:110: RuntimeError"}, "description": "\n    1. 通过参数化读取 CSV 中的多个用户账户和密码。\n    2. 使用传入的 browser fixture 启动浏览器实例。\n    3. 调用登录页面的 login_with_credentials 方法执行登录。\n    4. 记录登录操作的响应时间，方便性能评估。\n    5. 登录失败时截图并抛出异常，确保测试失败可追踪。\n    ", "attachments": [{"name": "log", "source": "f6360bd0-d65f-4ae3-bc7a-6bf5f706ff6f-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "user_data", "value": "{'username': 'lw_test_加盟商', 'password': 'abc123456'}"}], "start": 1754984305413, "stop": 1754984305413, "uuid": "2c8dd705-1a15-4e1f-9f09-8b4d1f5e6f2b", "historyId": "7c6f39f548a4b2689ca9a3029a492327", "testCaseId": "41a98be2e5ba8dfd29fb449496735cd9", "fullName": "tests.test_login_performance#test_login_performance", "labels": [{"name": "feature", "value": "登录性能测试"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_performance"}, {"name": "host", "value": "DESKTOP-I66F8NN"}, {"name": "thread", "value": "12412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_performance"}]}